"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['snakeGame.py']
DATA_FILES = [
    "assets",
    "Snake.py",
    "Apple.py",
    "Banner.py",
    "Level.py",
]
OPTIONS = {
    "iconfile": "assets/img/icon/icon.icns"
}

setup(
    name="Snake",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
